
spring:
  datasource:
    name: exam_practice_system #数据库名
    url: jdbc:mysql://localhost:3306/exam_practice_system?charactorEncoding=utf8mb4&serverTimezone=CST #url ?serverTimezone=GMT%2B8&useSSL=true
    username: root #用户名
    password: cyq032517 #密码
#    driver-class-name: com.mysql.jdbc.Driver #数据库驱动

#mybatis:
#  mapper-locations: classpath:mapper/*.xml #配置映射文件
#  type-aliases-package: com.rgobj.generalproblemdemo.bean #配置实体类